version: '3'
services:
  nginx:
    image: "nginx:alpine"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./web:/opt/web
      - ./certs:/certs
    ports:
      - "80:80"
      - "443:443"
